export enum FA2Errors {
    FA2_TOKEN_UNDEFINED = "FA2_TOKEN_UNDEFINED",
    FA2_NOT_OWNER = "FA2_NOT_OWNER",
    FA2_NOT_OPERATOR = "FA2_NOT_OPERATOR",
    FA2_INSUFFICIENT_BALANCE = "FA2_INSUFFICIENT_BALANCE",
  }